### ISSUE TITLE
Students get logged out instead of redirected to the dashboard when completing ROAR-MEP

### ISSUE THREAD

**Issue by jasetran** [yeatmanlab/roar#102]
- Carroll Students were logged out the dashboard when they completed Under the Sea (ROAR-MEP)
- They were still able to log back in and play the games, but it was annoying to log their students back in again

**Comment by richford** [comment]
Closed as students are now being redirected back to the new dashboard. @jasetran , please verify and reopen this issue if you find that it persists.
