### ISSUE TITLE
Login: New administrator for CA San Carlos, can login but can't see admin

### ISSUE THREAD

**Issue by tonyamurray** [yeatmanlab/roar#107]
I created a new administrator tonyamurray@stanford.edu (Note this is my full name and not my usual tonyamur account) and assigned it to CA San Carlos.  I logged in ok via the magic link, but can’t see the administration.

This was done via pr-link: https://gse-roar-admin--pr182-enh-refactor-partici-zs558iap.web.app/

<img width="1754" alt="image" src="https://github.com/yeatmanlab/roar/assets/40304930/4fbc0068-5cb8-4de7-8a4d-e116d0eac881">

**Comment by jasetran** [comment]
This also happened to me when I assigned an administrator (readingresearch@stanford.edu) to AIM Academy. See screenshot here:
<img width="1920" alt="Screenshot 2023-11-09 at 11 00 59 AM" src="https://github.com/yeatmanlab/roar/assets/100793918/8a5e0f42-7eab-4ddd-90e7-ec6786104bcf">

**Comment by richford** [comment]
Added to backlog as https://app.clickup.com/t/8686cnwng
