### ISSUE TITLE
multiple Apps are double logging data (2 unique runs) in the firebase at the beginning of the game

### ISSUE THREAD

**Issue by AnyaWMa** [yeatmanlab/roar#109]
At least in Vocab, SWR, and CVA, each participant will init two unique runs in database at the beginning. 

Suggest urgency: urgent

**Comment by jasetran** [comment]
could you send you firebase link as an example? i want to check to see if it's happening in other apps

**Comment by richford** [comment]
Likewise, I'd like to see a firebase link as an example. I had trouble reproducing the issue.

**Comment by AnyaWMa** [comment]
this is closed given no duplicate runs, just duplicate variants.
