### ISSUE TITLE
Registered task isn't showing up in the task dropdown menu when trying to register a new variant (Deadline: 11/5/2023)

### ISSUE THREAD

**Issue by jasetran** [yeatmanlab/roar#110]
- I am trying to register two new variants for ROAR-ANB and the task ID isn't showing up from the dropdown menu.
![Screenshot 2023-11-03 at 3 50 13 PM](https://github.com/yeatmanlab/roar/assets/100793918/c74dec5c-42d5-42ae-b586-d99c0ec69a46)

**Comment by richford** [comment]
This turns out to be expected behavior. Tasks can have a special "registered" tag in the database and the drop down only shows these registered tasks. This PR adds a toggle to show/hide the unregistered tasks: https://github.com/yeatmanlab/roar-dashboard/pull/187
