### ISSUE TITLE
Score Report is broken

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#111]
The score reports are showing all students as needing support on everything. The percentiles and standard scores aren't showing up. The exported csv is also missing percentiles and standard scores.

<img width="390" alt="image" src="https://github.com/yeatmanlab/roar/assets/35785147/90cf0fd7-98db-43a7-8614-b7c84e764eca">

<img width="375" alt="image" src="https://github.com/yeatmanlab/roar/assets/35785147/6f0bae15-3ff0-4f21-8e8f-4623c50dd9e6">

<img width="600" alt="image" src="https://github.com/yeatmanlab/roar/assets/35785147/2c2122b5-5711-43cb-be5b-7353eb147a58">

**Comment by richford** [comment]
Resolved via admin-sdk
