### ISSUE TITLE
roarquery: PID missing from Letter runs output

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#113]
I pulled all Letter data with the following command:
roarquery runs --task-id=letter letter.csv

The output does not contain the PID field, so there is no way to link the data to other student data.

> names(letter.orig)
[1] "runId"         "assigningOrgs" "completed"     "taskId"       
[5] "timeFinished"  "timeStarted"   "variantId"     "CreateTime"   
[9] "scores"

**Comment by richford** [comment]
Can you tell me your version of roarquery using
```
roarquery --version
```

**Comment by tonyamur** [comment]
This was solved by doing conda activate my_env
