### ISSUE TITLE
Cannot see the school-level progress and score reports if a school has multiple classes

### ISSUE THREAD

**Issue by jasetran** [yeatmanlab/roar#114]
- Not sure if this is a bug or enhancement 
- I can't see progress or score reports across all Carroll School classrooms
<img width="942" alt="Screenshot 2023-11-07 at 12 40 28 PM" src="https://github.com/yeatmanlab/roar/assets/100793918/735efe32-1e02-459e-83e2-643f5fc7bbc9">

**Comment by richford** [comment]
Added to backlog as https://app.clickup.com/t/8686cnwng
