### ISSUE TITLE
Scores are not showing up correctly for AIM Academy score reports

### ISSUE THREAD

**Issue by jasetran** [yeatmanlab/roar#121]
- Progress tracker shows that 127 students have completed, but there are only scores showing up for PA
- Standard scores and percentiles are showing up as empty colored circles 
- They should also have scores for SWR and SRE
<img width="924" alt="Screenshot 2023-11-08 at 12 43 39 PM" src="https://github.com/yeatmanlab/roar/assets/100793918/baa20c6d-b4fa-488c-8fcd-0ce56d4ef322">

**Comment by richford** [comment]
This was resolved using the admin SDK to refresh corrupted scores
