### ISSUE TITLE
Can't see administration progress or score reports for AIM Academy or Carroll School admin accounts

### ISSUE THREAD

**Issue by jasetran** [yeatmanlab/roar#123]
When I log into the admin account (readingresearch@stanford.edu), I can't see any administrations. I see that AIM is listed as an organization in the List Organization window. This is also happening to Carroll School.
![Screenshot 2023-11-10 at 4 08 44 PM](https://github.com/yeatmanlab/roar/assets/100793918/6a621819-01c0-4946-a27b-3cbd9ff92e7f)

**Comment by richford** [comment]
Recorded in Backlog as https://app.clickup.com/t/8686d7tzv
