### ISSUE TITLE
Remove extra students from CA San Carlos Fall 23-24 admininistration

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#124]
In the CA San Carlos Fall 23-24 admin, remove students from the current administration (but not the database) who participated in the summer but were not shared via Clever for the fall. A list of names has been sent to @richford by secure email

We cannot encourage administrators from San Carlos to try out the progress and score reports until this issue is fixed.  This is time-sensitive, after Nov 20 we might as well wait until the next administration.

**Comment by tonyamurray** [comment]
I am meeting with San Carlos on Friday 12/1, and need this to be able to give them access to the online score reports.
