### ISSUE TITLE
Letter - Stochastic CSS behavior???

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/roar#14]
Not critical but annoying. The first time I launched ROAR-Letter on my iPad the CSS was a total mess and text was unformatted and on top of other text. And then I refreshed and launched again and everything was fine.

This isn't critical in that I could still hear the audio and play the game. But it looked terrible the first time it was launched. And stochastic behavior is worrisome. Marked as urgency high because I think we need to resolve this ASAP but it is not critical for Monday

**Comment by ctflores** [comment]
I had the same issue, except every time I refreshed, I got new errors.

**Comment by ctflores** [comment]
This is an example of a typical error that happens consistently throughout the game (on iPad): 
![IMG_2099](https://github.com/yeatmanlab/roar/assets/35785147/63a4f5b2-9fdd-47cc-bc66-16454081aaa9)

**Comment by ctflores** [comment]
![IMG_2100](https://github.com/yeatmanlab/roar/assets/35785147/4e2d8273-7882-4a82-a0fd-115d08e6342a)
![IMG_2101](https://github.com/yeatmanlab/roar/assets/35785147/ed0b45ed-ad9e-4783-b948-0af673738c8a)

**Comment by Zio-4** [comment]
Leaving this comment as a note: Proper assets are not being preloaded? Happened in PA as well before fixing.
