### ISSUE TITLE
(All assessments - iPad) Audio doesn't stop after hitting back arrow on browser

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#17]
If you hit the back arrow to return to the dashboard, the audio file keeps playing until it's done. Probably not a huge deal, but it's a bit funny.

**Comment by tonyamur** [comment]
This is related to #6

**Comment by richford** [comment]
I believe this is resolved via https://github.com/yeatmanlab/roar-dashboard/pull/99. I'll close for now but if it returns, please do reopen this issue.
