### ISSUE TITLE
SWR - ES is in english on dashboard

### ISSUE THREAD

**Issue by Zio-4** [yeatmanlab/roar#2]

**Comment by tonyamur** [comment]
Also, press any key did not work to advance to next screen

**Comment by ctflores** [comment]
This is a big deal, and we would like to be able to create a video for the Colombian school and the RAs next week (Wednesday)

**Comment by richford** [comment]
This is resolved in https://github.com/yeatmanlab/roar-swr/pull/135

**Comment by richford** [comment]
Closing as completed
