### ISSUE TITLE
Phoneme not computing scores at run level

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#21]
I just tested the phoneme-school variant for Howard Lower.  You can see my data with assessmentPid: hwsch-test-4, run: LvXClBIE8Dxv33tCS64H.

Trial data appears correct.
Run data does not expose computed nor raw scores
This will eventually affect the generation of score reports.
![image](https://github.com/yeatmanlab/roar/assets/83736178/783fd4bf-a9e1-4628-9003-b55e08c409cf)

suggested tag: urgency:low

**Comment by jyeatman** [comment]
Is this related
<img width="940" alt="image" src="https://github.com/yeatmanlab/roar/assets/1775818/95033103-a10c-41a5-bdc8-d31e4acfb2af">

**Comment by richford** [comment]
Resolved in https://github.com/yeatmanlab/roar-dashboard/pull/99
