### ISSUE TITLE
SWR - ES CSS issues (iPad

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#22]
SWR - Es has the same CSS issues as SWR - En on iPad. Urgency is lower because we don't have anyone on deck to use SWR on iPad this month.

**Comment by ctflores** [comment]
![IMG_2102](https://github.com/yeatmanlab/roar/assets/35785147/e28d7435-67d2-4b34-afde-0bbd02ea0480)

**Comment by Zio-4** [comment]
I'm going to close this since this is a duplicate of #18 . The CSS is the same regardless of language so no need to open issues for each language version. It might look a little different just because the amount of text from translations moves the element slightly more or less.
