### ISSUE TITLE
Exceeded quota for email lookup when trying to create student accounts

### ISSUE THREAD

**Issue by jasetran** [yeatmanlab/roar#29]
- I got an error when trying to generate accounts for Howard School students: `FirebaseError: Firebase: Exceeded quota for email lookup. (auth/quota-exceeded).`
- 110 of the 294 accounts were uploaded successfully, but 184 accounts failed

<img width="651" alt="Screenshot 2023-09-04 at 12 11 37 AM" src="https://github.com/yeatmanlab/roar/assets/100793918/3d0dd4c8-37a5-4a69-8c3e-a4aecd914d24">

**Comment by richford** [comment]
This is resolved in [roar-firekit PR 61](https://github.com/yeatmanlab/roar-firekit/pull/61)
