### ISSUE TITLE
ROAR apps don't play audio on intro trials consistently on iPad

### ISSUE THREAD

**Issue by Zio-4** [yeatmanlab/roar#3]
Audio does not play consistently on Chrome on iPad.

**Comment by richford** [comment]
This is for all ROAR apps? Letter, Word, Sentence, Phoneme?

**Comment by richford** [comment]
Reposting comment from the duplicate #7 

> Consistently seen on iPad before 8/30, currently not occurring.
Affects Letter, SWR, SRE; greatest concern is for Letter.
Known iOS issue where after entering fullscreen mode, audio does not play until after user clicks screen.
