### ISSUE TITLE
Report an issue / having trouble button

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/roar#31]
We should add a button somewhere for users to note any issues / bugs and also to provide feedback. One thought is that it could submit any issues / feedback / bugs to a slack channel or to a github issue (with a slack integration) so that we are notified quickly and so that devs and partnerships can both see feedback in real time. We could have a form with a text entry box and some radio buttons to help route the issue to the right place (ie tag the right people on slack / gh)Tagging @ctflores and @richford for thoughts on this non-urgent enhancement.

**Comment by jyeatman** [comment]
Temporary- link to static google form

@richford can we add a link on the dashboard at the bottom or top of every page that links to a satin google form to report bugs?

**Comment by richford** [comment]
This was added to the product backlog: https://app.clickup.com/t/8685n2g3f
