### ISSUE TITLE
Change display when all assigned games are complete

### ISSUE THREAD

**Issue by tonyamurray** [yeatmanlab/roar#33]
While taking snapshots to tell BRSSD teachers about the changes to the dashboard, I realized that when all games are complete the screen looks like this:
![image](https://github.com/yeatmanlab/roar/assets/40304930/fc668d9a-bcc5-46d4-9be4-e441cd11eabe)

Even though all three games are checked and green, it might not be obvious to some users (and teachers walking by) that they are done.  I'd suggest an enhancement to have a different graphic (maybe the ROAR logo) and "All tasks completed" be displayed (maybe this goes on a new, 4th tab?), while still allowing the ability to replay games.

**Comment by tonyamur** [comment]
It was also requested by a BRSSD Nesbit teacher that the games be locked down after they are complete.  Jason suggested adding a query parameter:
lockwhendone=true/false

**Comment by richford** [comment]
This was added to the backlog at https://app.clickup.com/t/8685tevz9
