### ISSUE TITLE
Reopen issue "can't press a key to continue" when replaying ROAR-Word after exiting the full screen

### ISSUE THREAD

**Issue by tonyamurray** [yeatmanlab/roar#34]
After finishing all 3 games and  seeing the green checkmarks, I relaunched ROAR-Word again, and cannot press any key to continue.  This persisted through a refresh of the dashboard. Two or three refreshes later, I was able to launch and use keys to advance.

**Comment by AnyaWMa** [comment]
ROAR-Sentence and ROAR-Word: when refresh/return back, the audio keeps playing and when re-enter, I cannot press any key to continue. 

ROAR-Word: when exit full screen (during test trials), I cannot press any key to continue, even when I re-enter full screen.

**Comment by AnyaWMa** [comment]
tagging @richford for visibility

**Comment by richford** [comment]
This was resolved in dashboard PRs [122](https://github.com/yeatmanlab/roar-dashboard/pull/122) and [129](https://github.com/yeatmanlab/roar-dashboard/pull/129)
