### ISSUE TITLE
SRE mobile: stimulus too big 

### ISSUE THREAD

**Issue by AnyaWMa** [yeatmanlab/roar#35]
<img width="711" alt="Screenshot 2023-09-07 at 10 44 43 AM" src="https://github.com/yeatmanlab/roar/assets/76414800/89021671-74d9-406b-95fa-33630665b821">

stimulus too big for mobile, which will challenge the validity of speed reading, especially for long sentence. Ideally the text should be as consistent as SWR size.

**Comment by AnyaWMa** [comment]
This can be solved by this PR: https://github.com/yeatmanlab/roar-sre/pull/63

**Comment by richford** [comment]
This has been added to the backlog at https://app.clickup.com/t/8685tjhyj
