### ISSUE TITLE
Setting up Administrations by classroom is nearly impossible because the dropdown box is innavigable

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#36]
This issue prevents us from assigning ROAR by grade-level within schools. It is not possible to know what classroom belongs to what school within this list. This will only get worse when Springfield schools sync up. 

https://github.com/yeatmanlab/roar/assets/35785147/1cd8e78f-3fd9-4005-808e-0dfbeb50ab01

**Comment by richford** [comment]
Added to backlog as https://app.clickup.com/t/86860ytvd
