### ISSUE TITLE
Feature Request: Display variants and abbreviations to enable checking of administration setup

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#38]
This is a feature request.  For anything that is entered in the course of setting up an organization and an administration, there should be a corresponding display where research coordinators can later go back and view to confirm that everything is set up correctly. The initial items I've noticed are needing to verify the exact variant that is configured for an administration, and to look up the abbreviations that are set at the district and school level.

**Comment by richford** [comment]
The abbreviations are available now in list-orgs. The variant info item has been added to the backlog at https://app.clickup.com/t/8685tedfe
