### ISSUE TITLE
Sentence run missing subscores

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#44]
This Sentence run for PID d2ef0f28  was done from a clever impersonation from #DEMO ROAR Stanford via the CA BRSSD Fall 2023 administration, with variant sentence-school-3minParallelAIFormV1

The run shows it is complete but there is no scores object:
<img width="458" alt="image" src="https://github.com/yeatmanlab/roar/assets/83736178/5700af44-c757-4cc4-8a02-f7307db78aea">

https://console.firebase.google.com/u/0/project/gse-roar-assessment/firestore/data/~2Fusers~2FOZAN1SUpAaTPe1ydzvnBMp2ruU02~2Fruns~2FLRR4mKEE5dXZMakL3CYk

**Comment by richford** [comment]
This happened for a Howard student as well:

Here is a run from a Howard student with scores in the run doc: https://console.firebase.google.com/u/1/project/gse-roar-assessment/firestore/data/~2Fusers~2F192RjezkHWQVNYJNjNLhmyMSEh22~2Fruns~2FWUKsDo9AGq5Y4xlM4MTx

And here is one from a Howard student with no scores in the run doc:
https://console.firebase.google.com/u/1/project/gse-roar-assessment/firestore/data/~2Fusers~2F1AY86Z4lkQPZaLf3MoiNGOF01xQ2~2Fruns~2FLlOg48FSIdLvS63saimd

**Comment by richford** [comment]
Resolved in [dashboard PR 114](https://github.com/yeatmanlab/roar-dashboard/pull/114) and accompanying ROAR app PRs
