### ISSUE TITLE
After signing out, ROAR does not log back in to dashboard

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#45]
I have tried this multiple times and had the same issue several times. I logged into roar.education as a student. I clicked "Sign Out." Then I tried to log in as a new student. It got hung up and never logged in. I waited for a couple of minutes, and it still never logged in. 

This is a problem because we will have students sharing laptops from one period to the next, and students in the second period will not be able to log in. This will affect the Colombian administration Wednesday. 

![image](https://github.com/yeatmanlab/roar/assets/35785147/744a169e-c96d-420c-a46f-051c3ff367fd)

![image](https://github.com/yeatmanlab/roar/assets/35785147/b8e1ad7a-c011-4803-9b95-526395eb8a4f)

**Comment by ctflores** [comment]
It does work upon refreshing the page, but we don't want to have to ask the Colombian students to do that.

**Comment by richford** [comment]
I can replicate this in Chrome, but not Brave.
