### ISSUE TITLE
ROAR-Letter:  Intermittent - audio has crackling sound on iPad

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#47]
I tested ROAR-Letter with both my laptop and iPad at home (so same wifi connectivity).  The sound quality of all audio on the iPad (both instructions and stimulus) had a crackling, static sound underlying the actual audio.  The login was through the dashboard.  It persisted through one refresh.  ROAR-Phoneme did not have the same crackle.  When I launched ROAR-Letter again, the crackle was gone.

**Comment by ctflores** [comment]
I notice this sometimes too. I agree it isn't consistent. I just figured it was my computer until you posted this.

**Comment by ctflores** [comment]
I'm marking it urgency: medium because while it doesn't impair game play, it does affect how we are perceived by schools and Reading Reimagined, and we will have a lot of eyes on Letter in the next few weeks.
