### ISSUE TITLE
Feature Request:  Add username column to Progress datatable 

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#49]
Some of the Reading Reimagined schools are not giving us first and last names, only usernames (or having us generate the user names, which they will keep track of locally).  The Progress display has First Name, Last Name, and PID, and there is no way to tie this back to the username that was uploaded.  (For example see 1036test001 in SD Friends RC Fall 23-24, which has PID of foc-rc-80ab68a).  This will cause difficulty in communicating back to schools which students have or have not completed ROAR, and could also be an issue for score reporting (when that becomes available).

**Comment by richford** [comment]
This has been implemented
