### ISSUE TITLE
ROAR - Palabra is unplayable without refreshing. Words bounce and display over each other

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#51]
I have had this issue with ROAR-Palabra through multiple tests with different test users. When a user enters ROAR-Palabra for the first time, the words and plus-signs bounce as they display, and words display over each other. See the video for examples. In the video, every word is bouncing, and twice you will see examples of words displaying over each other. 

After refreshing, the game plays perfectly fine. 

Without this bug fix, we can not let Colombia take this version Wednesday. 

https://github.com/yeatmanlab/roar/assets/35785147/f64bc970-6351-46f0-98a2-7564f5ff7c57

**Comment by ctflores** [comment]
Upon refreshing, the game plays perfectly fine.

**Comment by ctflores** [comment]
<img width="1418" alt="image" src="https://github.com/yeatmanlab/roar/assets/35785147/d791842f-cf4c-455e-a723-7ab6efd57a0f">


<img width="1263" alt="image" src="https://github.com/yeatmanlab/roar/assets/35785147/3b6896c7-6df6-4f05-8965-49843ef23389">

**Comment by richford** [comment]
Closed via cache busting.
