### ISSUE TITLE
Administration cards and organization list for administrator view are permanently loading/broken

### ISSUE THREAD

**Issue by jasetran** [yeatmanlab/roar#53]
- The administrator view is permanently loading. See screenshots below: 
![Screenshot 2023-09-08 at 11 38 57 AM](https://github.com/yeatmanlab/roar/assets/100793918/c075f4ff-cc4a-4592-a276-dc4a5c198c7f)
![Screenshot 2023-09-08 at 11 42 16 AM](https://github.com/yeatmanlab/roar/assets/100793918/f4e8811e-d08f-4afe-900b-8276c6054c70)

**Comment by richford** [comment]
Resolved. @jasetran, please reopen if this happens to you again, but I believe this was a transient caching issue.
