### ISSUE TITLE
SWR freezes in the middle of the game, won't accept arrow key input

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#55]
I saw this about a dozen times at BRSSD today. Student would be playing SWR and in the middle of the game during regular trials the screen would freeze and wouldn't accept arrow key input.  It varied when it would happen, could be near the beginning, in the middle, or near the end. It was still possible to hit Esc to get out of full screen, and then recover by either back button or closing the tab and relaunching ROAR. 

Note that a few students repeatedly saw this with SWR on the same chromebook, and we resorted to either rebooting or switching to another chromebook.  For some students who were very near the end of SWR, I directed them to move on to PA or SRE, and they did not have any issues with those games.

Alby reported seeing this in her classes as well.

**Comment by richford** [comment]
This was resolved in roar-dashboard PRs [122](https://github.com/yeatmanlab/roar-dashboard/pull/122) and [129](https://github.com/yeatmanlab/roar-dashboard/pull/129)
