### ISSUE TITLE
Admin View - Can't see student names to check on progress

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#56]
Colombia needs to know who still needs to ROAR, but the progress table only reports pid, not usernames or First/Last Names. I did upload first names and usernames, but neither showed in the table on the progress page. 

<img width="297" alt="image" src="https://github.com/yeatmanlab/roar/assets/35785147/48aabedd-cb1c-4d92-8112-bcd031f246e6">

**Comment by tonyamur** [comment]
See also #57

**Comment by richford** [comment]
This has been added to progress table and score reports
