### ISSUE TITLE
Names not uploading from csv upload 

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#57]
When we upload csvs, the first and last names are not showing up in firebase. Only Clever users have name.first and name.last in firebase.

For example, I uploaded the Colombian students, and Tonya uploaded a test group to "Test Choicer School," and we can see the students in firebase, but their names are not included in the firebase document. 

This is related to github issue #56

**Comment by tonyamur** [comment]
Also, one day is subtracted from the DOB before storing it to firebase.  I've attached my test upload.  You can see in the file that the DOB should be 07/01/2007, but in firestore it is listed as June 30, 2007.
[Choice Charter Test acct.csv](https://github.com/yeatmanlab/roar/files/12602456/Choice.Charter.Test.acct.csv)
