### ISSUE TITLE
Admin view - Variant list not displaying names of tests

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#58]
The Variant list includes several variants that just look like this. I'm unsure if it's indicative of a bigger problem: 
<img width="388" alt="image" src="https://github.com/yeatmanlab/roar/assets/35785147/74c71c4e-a530-4206-8199-6eb67787c2c5">

**Comment by richford** [comment]
The variant displays the variant ID if and only if the name is unavailable. This indicates that a name has not been assigned to this variant. Closing as not an issue.
