### ISSUE TITLE
All Apps: When re-entering the game, press any key did not advance

### ISSUE THREAD

**Issue by richford** [yeatmanlab/roar#6]
From @tonyamurray: press any key did not work to advance to next screen

**Comment by ctflores** [comment]
Wednesday Sept 6

**Comment by tonyamur** [comment]
I was just able to recreate it, but it’s a very edge case.  I hit ESC and then back button to go back to the dashboard.  The audio was still playing, and I launched Word-ES again.  The audio restarted, but now even after it finishes it doesn’t accept keyboard input.  I suspect there are actually two instances running somehow

**Comment by tonyamur** [comment]
Refresh clears it.  It can be a workaround we recommend for troubleshooting.

**Comment by tonyamur** [comment]
I just recreated it in Word as well, but this time I could hear audio from both versions that were running.  Also in Sentence.  Basically things stick around even though you press the Back button.  For Phoneme, the mouse arrow disappears in the new game, but I can still click the screen and move on (and the mouse comes back on the next screen)

**Comment by jyeatman** [comment]
I was able to reproduce as well. After exiting an app by hitting the back button keypresses will not register when the app is launched again

**Comment by AnyaWMa** [comment]
My guess about this problem is the app is not completely ended after returning to the dashboard, that’s also why audio is still playing after you go back to main menu.

**Comment by jyeatman** [comment]
@richford 's fix solves the issue for refresh but not for back arrow. A refresh now resets everything and games work again. But a back arrow causes the same problem (until refreshed)

**Comment by Zio-4** [comment]
On Adams fix I can't reproduce the back arrow bug on desktop or mobile (iPad). @jyeatman  Could you do a hard reload and try again?

**Comment by jyeatman** [comment]
All fixed! Adam’s new push fixed everything for me (sorry responded in slack but not GitHub). Also tested on iPad and everything worked no matter how hard I tried to break it

Jason D. Yeatman, Ph.D.<https://profiles.stanford.edu/jason-yeatman>
Associate Professor
Stanford University, Graduate School of Education and Department of Psychology
Stanford School of Medicine, Division Developmental Behavioral Pediatrics
Brain Development & Education Lab<http://brainandeducation.com/>
________________________________

**Comment by richford** [comment]
Resolved in https://github.com/yeatmanlab/roar-dashboard/pull/99
