### ISSUE TITLE
SRE mobile: students can respond while touching white area near the button 

### ISSUE THREAD

**Issue by AnyaWMa** [yeatmanlab/roar#62]
![image](https://github.com/yeatmanlab/roar/assets/76414800/3efdc10c-e0ef-4b36-8c0c-687e16974581)

SRE mobile: students can respond while touching white area near the button. This will challenge the validity of the task. 

SWR mobile doesn't have this issue. I think we should 
1. change the button img to remove the white area 
2. config the app to only allow response when touching the img instead of touching the margin area of the btn-group. 

@jasetran for visibility

**Comment by richford** [comment]
This has been added to the backlog at https://app.clickup.com/t/8685tjh5j
