### ISSUE TITLE
External task launcher

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/roar#63]
For LEVANTE we will need the dashboard to be able to interact with external tasks, not hosted on the dashboard. This might be an externally hosted jsPsych experiment or another online tool that accepts configuration parameters through a quarry string. To achieve this we would want to be able to register a "task" in the dashboard that consists of:
- An external URL with quarry string parameters such as participant ID, age, grade, and any other de-identified information that we want to pass to this external task
- A redirect URL that brings the participant back to the dashboard and passes parameters back through a quarry string like participant ID, completion status and maybe even data

To achieve this and have it "feel" as if the external task is running in the dashboard we can open the external URL in a fullscreen iframe so that the participant never sees that they are being redirected.

In terms of timeframe, this would be a good enhancement for late october / early november. Tagging @mcfrank for visibility

**Comment by richford** [comment]
This has been added to the backlog at https://app.clickup.com/t/8685tjk6g

**Comment by jyeatman** [comment]
I see the stale tag but I think @Zio-4 said he's almost done right?

**Comment by Zio-4** [comment]
This is on pause due to priority and figuring out how / what we want to track from the external tasks. The first part however is implemented, you can register an external task and it can be played, there just isn't anything to route back to the dashboard and record that data.

**Comment by jyeatman** [comment]
So we could register and launch an external task and we could have that task redirect back to the dashboard but nothing would be logged about completion?

A simple way to finish this up would be to long task launching as completion for the time being

**Comment by Zio-4** [comment]
Yes, that can work. I don't think this is a priority though, is it? The rest of the ROAR apps are in queue to be converted to packages for native dashboard integration.

**Comment by jyeatman** [comment]
If it is **easy** to implement that then I think you should so that this can be **finished for now**
And then folks could start using this as a means to pilot new measures

**Comment by Zio-4** [comment]
Got it.
