### ISSUE TITLE
Users list isn't showing up for administration card 

### ISSUE THREAD

**Issue by jasetran** [yeatmanlab/roar#64]
- I can't check which users have completed the REDCap validation to pay them 
- The users don't show up under REDCap Validation: 
<img width="1425" alt="Screenshot 2023-09-18 at 11 22 34 AM" src="https://github.com/yeatmanlab/roar/assets/100793918/8cb5d3ee-9b66-4b55-bfab-6c834a2c6644">

**Comment by richford** [comment]
This should be resolved now. Closing as resolved. @jasetran please reopen if I'm mistaken.
