### ISSUE TITLE
SWR and SRE - After ending, students have to sign out and sign back in to move forward with the next game.

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#65]
This was an issue in Choice Charter this morning. 

I tested with 1033-test004 on the chromebook, and I experienced the problem. I finished SWR, and my run was registered in firestore as completed. When it was finished, it took me back to the dashboard, but it didn’t look like I had finished the game at all.
![IMG_4932](https://github.com/yeatmanlab/roar/assets/35785147/31478983-f1e1-4a49-b5d8-f8ed0c9b1ce6)
![IMG_4933](https://github.com/yeatmanlab/roar/assets/35785147/df9a6e1d-2be1-4621-bb8a-ad712b89a3a5)

Because the order is locked, I can’t take SRE, even though i did SWR

Refreshing the page doesn't help. 

If I sign out and sign back in, it's fine. 
![IMG_4934](https://github.com/yeatmanlab/roar/assets/35785147/1598fd96-18cb-408b-bb1a-fb0468631dc3)

**Comment by ctflores** [comment]
I'm not sure if this is SWR-specific. The same thing happened with the same user after SRE.

**Comment by aungashe** [comment]
I just tested it as well as user 1033-test005 and had the same exact issue for both.

**Comment by richford** [comment]
This was resolved in https://github.com/yeatmanlab/roar-dashboard/pull/129
