### ISSUE TITLE
Roarquery - no birth year for half of students

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#77]
Out of 2190 completed Springfield SWR assessments, 1331 are missing user.birthYear. These students have an estimated WJ, so presumably they had a birthyear record somewhere?

These aren't limited to specific schools. I can't find a pattern to the students missing birthyear. 
<img width="598" alt="image" src="https://github.com/yeatmanlab/roar/assets/35785147/25f72f1a-9b1f-4370-abe4-b2633dee6870">

This is preventing us from creating ROAR norms for Springfield.

**Comment by richford** [comment]
This should be resolved now. I reran the cloud function to sync ages. There are still 71 users in the assessment DB who came from clever and are missing birthMonth and birthYear, but they are all admins or educators for whom Clever does not give us a DOB.
