### ISSUE TITLE
roarquery - birth year

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#82]
We are still missing birth year from a large number of Springfield students. 

This table reflects SWR completed trials: 

<img width="545" alt="image" src="https://github.com/yeatmanlab/roar/assets/35785147/70d1635d-6f1e-49f4-ab5d-db6b1ac6db0e">

**Comment by richford** [comment]
Recorded in backlog as https://app.clickup.com/t/868607tvu
