### ISSUE TITLE
Springfield students consistently kicked out of test

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#83]
Hello Carrie,

My teacher also sent me this picture and said the students are all getting kicked out when they complete the amount of progress shown in the picture.  Thank you for letting me know about the student.  Have a great day.

Antonella

Antonella Raschilla Manzi

Assistant Principal
Roger L. Putnam Vocational Technical Academy
1300 State Street
Springfield, MA 01109
(413)787-7424

From: Bartlett, Jonathan <[bartlettj@springfieldpublicschools.com](mailto:bartlettj@springfieldpublicschools.com)>
Sent: Friday, October 6, 2023 11:35 AM
To: Raschilla, Antonella <[raschillaa@springfieldpublicschools.com](mailto:raschillaa@springfieldpublicschools.com)>; Codding, Amanda <[coddinga@springfieldpublicschools.com](mailto:coddinga@springfieldpublicschools.com)>
Subject: ROAR Test Glitch
 
Hi,
In case you can pass this along to the testing people: the spot on the progress bar in the attached photo is where almost half of my class has had their test freeze, forcing them to re-do the section.
Thanks and have a great weekend,
Jon Bartlett
Teacher of English Language Arts
Putnam Vocational-Technical Academy
Google Voice number: (413) 341-0816

![thumbnail_IMG_9415](https://github.com/yeatmanlab/roar/assets/35785147/f8d10dc6-8480-4748-95a3-29a9b9973134)

**Comment by richford** [comment]
Recorded in backlog as https://app.clickup.com/t/868607uz5
