### ISSUE TITLE
ROAR-SRE "grade" reading incorrect 

### ISSUE THREAD

**Issue by AnyaWMa** [yeatmanlab/roar#84]
https://github.com/yeatmanlab/roar-sre/blob/main/src/experiment/scores.js 

Currently, many clever users were assumed 1st graders.

line 24: If grade is a string value (which likely happen in clever users), then it uses grade.min. 

Solution: change string to int, and don't assume grade.min. 

suggested urgency: critical

**Comment by richford** [comment]
Recorded in backlog as https://app.clickup.com/t/868607nrc
