### ISSUE TITLE
Scores view:  First and Last names disappear when switching from colors to scores

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#88]
Choice Charter may be among the few csv uploads that provide both usernames and First & Last names.  In the Scores view, when I switch from Color to one of the scores, all the names disappear (although the usernames remain).

**Comment by tonyamur** [comment]
I just realized the name columns aren't gone, they just narrowed so much that it looked like they had disappeared.

**Comment by richford** [comment]
Resolved in https://github.com/yeatmanlab/roar-dashboard/pull/170
