### ISSUE TITLE
Scores export doesn't indicate the data type in column header of csv

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#89]
When I export to csv from the Scores view, the column headers do not indicate whether the numbers are for raw scores, standard scores, or percentiles.  It actually would be preferable to export all 4 values (color, raw, standard, percentile) at once, not to select each value and then export.

Export when color is selected does not give columns for support level (or even the displayed color name).

**Comment by richford** [comment]
Resolved in https://github.com/yeatmanlab/roar-dashboard/pull/170
