### ISSUE TITLE
Scores:  SMFC score report doesn't load

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#93]
I am able to see other score reports (BRSSD and Good Tutors), but nothing loads for SMFC (which has multichoice, and the administration window is still open.)

**Comment by tonyamur** [comment]
![image](https://github.com/yeatmanlab/roar/assets/83736178/a2c013a8-0518-476a-861e-b35aa5324c01)

**Comment by tonyamur** [comment]
Different set of errors today:
![image](https://github.com/yeatmanlab/roar/assets/83736178/25902437-702c-4090-b02b-008ec5827b56)

**Comment by richford** [comment]
Resolved in https://github.com/yeatmanlab/roar-dashboard/pull/173
