### ISSUE TITLE
Super Admin View - Create a new organization page doesn't show all districts

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#94]
I am trying to create a new administration for the DC folks to test ROAR tomorrow. I can’t create it because of the following:
1. I can’t upload students without having a district and school, which is fine. I created a district, "Test - ROAR Preview."
2. But when I go to add a school organization to my district, the district isn’t in the list of districts in the dropdown box in the Create a new organization page.
3. I tried refreshing and completely signing out and signing back in, and it still wasn’t there. I noticed that only 15 districts show up in the dropdown box for districts, but there are over 20 in the full list of district organizations.
![image](https://github.com/yeatmanlab/roar/assets/35785147/6d82cb38-3687-4247-938f-17491c7e6f64)

**Comment by richford** [comment]
Added to backlog as https://app.clickup.com/t/86860yua7
