### ISSUE TITLE
Super Admin View - Upload students errors are all over the map

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#95]
When uploading students, the error messages do not seem to match the actual issues. 

1. For example, it said the error was that the Group didn't exist, but actually the problem was that the username had already been taken. Once I switched the usernames, the students were uploaded to the group just fine.
2. For another example, it said, "FirebaseError: INTERNAL" for several users (see attached table), but the users appear in ROAR-Admin. I'm not too worried about these users, but should I be? 
[error-datatable-export.csv](https://github.com/yeatmanlab/roar/files/13183232/error-datatable-export.csv)

**Comment by richford** [comment]
Added to backlog as https://app.clickup.com/t/86866a2g5
